export const ORDER_STATUS = {
  DRAFT: 'Draft',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PRODUCTION: 'Production',
  PRODUCTION_DONE: 'PRODUCTION_DONE',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PENDING_BILLING: 'PENDING_BILLING',
  BILLED: 'BILLED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  CANCELLED: 'Cancelled',
  COMPLETED: 'Completed',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.DRAFT]: 'Draft',
  [ORDER_STATUS.PENDING_APPROVAL]: 'Pending Approval',
  [ORDER_STATUS.APPROVED]: 'Approved',
  [ORDER_STATUS.REJECTED]: 'Rejected',
  [ORDER_STATUS.PRODUCTION]: 'In Production',
  [ORDER_STATUS.PRODUCTION_DONE]: 'Production Done',
  [ORDER_STATUS.AWAITING_PAYMENT]: 'Awaiting Payment',
  [ORDER_STATUS.PENDING_BILLING]: 'Pending Billing',
  [ORDER_STATUS.BILLED]: 'Billed',
  [ORDER_STATUS.READY_FOR_DISPATCH]: 'Ready For Dispatch',
  [ORDER_STATUS.DISPATCHED]: 'Dispatched',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
  [ORDER_STATUS.COMPLETED]: 'Completed',
};

export const QUOTATION_STATUS = {
  OPEN: 'OPEN',
  CONVERTED: 'CONVERTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};
