import React from "react";
import {
  normalizeOwnership,
  quotationApprovalLabel,
  orderApprovalLabel,
  formatApprovalDisplay,
  formatPersonLine,
} from "../../utils/documentOwnership";

/**
 * Reusable ownership block for quotations, orders, invoices.
 * variant: "screen" | "print" | "compact" | "list"
 * docType: "quotation" | "order" | "invoice"
 */
export default function DocumentOwnershipPanel({
  data,
  docType = "order",
  variant = "screen",
  showGeneratedBy = false,
}) {
  const o = normalizeOwnership(data);
  const approval =
    docType === "quotation"
      ? quotationApprovalLabel(data)
      : orderApprovalLabel(data);

  const salesmanLine = formatPersonLine(o.salesmanName, o.salesmanRole, o.salesmanPhone);
  const approvalText = formatApprovalDisplay(approval);
  const approvalSub =
    !approval.pending && approval.at
      ? new Date(approval.at).toLocaleString("en-IN", {
          day: "2-digit",
          month: "short",
          year: "numeric",
          hour: "2-digit",
          minute: "2-digit",
        })
      : null;

  if (variant === "print") {
    return (
      <div className="qp-ownership-block">
        <div className="qp-pi-row">
          <span className="qp-pi-key">Salesman</span>
          <span className="qp-pi-val">{salesmanLine || "—"}</span>
        </div>
        <div className="qp-pi-row">
          <span className="qp-pi-key">Approved By</span>
          <span
            className="qp-pi-val"
            style={approval.pending ? { color: "#b45309", fontStyle: "italic" } : undefined}
          >
            {approvalText}
            {approvalSub ? ` · ${approvalSub}` : ""}
          </span>
        </div>
        {showGeneratedBy && (
          <div className="qp-pi-row">
            <span className="qp-pi-key">Generated By</span>
            <span className="qp-pi-val">
              {formatPersonLine(o.generatedByName, o.generatedByRole) || "—"}
            </span>
          </div>
        )}
      </div>
    );
  }

  if (variant === "list") {
    const pendingStyle = approval.pending
      ? { color: "#b45309", fontStyle: "italic" }
      : undefined;
    const salesDisplay = o.salesmanName || "—";
    return (
      <div style={{ fontSize: 11, color: "#64748b", marginTop: 4, lineHeight: 1.45 }}>
        <div>
          <span style={{ fontWeight: 600 }}>Salesman:</span> {salesDisplay}
        </div>
        {docType === "quotation" ? (
          <div>
            <span style={{ fontWeight: 600 }}>Approval:</span>{" "}
            <span style={pendingStyle}>{approvalText}</span>
          </div>
        ) : (
          <div>
            <span style={{ fontWeight: 600 }}>Approved by:</span>{" "}
            <span style={pendingStyle}>{approvalText}</span>
          </div>
        )}
      </div>
    );
  }

  if (variant === "compact") {
    return (
      <div style={{ fontSize: 12, color: "#475569", lineHeight: 1.5 }}>
        {salesmanLine && (
          <div>
            <strong>Customer owner:</strong> {salesmanLine}
          </div>
        )}
        <div>
          <strong>Approved by:</strong>{" "}
          <span style={approval.pending ? { color: "#b45309", fontStyle: "italic" } : {}}>
            {approvalText}
          </span>
          {approvalSub && ` · ${approvalSub}`}
        </div>
        {showGeneratedBy && (
          <div>
            <strong>Generated by:</strong>{" "}
            {formatPersonLine(o.generatedByName, o.generatedByRole) || "—"}
          </div>
        )}
      </div>
    );
  }

  const sectionStyle = {
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: "12px 14px",
    marginBottom: 14,
  };
  const row = { display: "flex", gap: 8, fontSize: 13, marginBottom: 6 };
  const label = { color: "#64748b", minWidth: 120, fontWeight: 600, flexShrink: 0 };
  const value = { color: "#0f172a", fontWeight: 500, flex: 1 };

  return (
    <div style={sectionStyle}>
      <div
        style={{
          fontSize: 11,
          fontWeight: 800,
          color: "#94a3b8",
          letterSpacing: "0.06em",
          marginBottom: 8,
        }}
      >
        OWNERSHIP
      </div>
      <div style={row}>
        <span style={label}>Customer owner</span>
        <span style={value}>{salesmanLine || "—"}</span>
      </div>
      <div style={row}>
        <span style={label}>Approved by</span>
        <span style={value}>
          <span style={approval.pending ? { color: "#b45309", fontStyle: "italic" } : {}}>
            {approvalText}
          </span>
          {approvalSub && (
            <span style={{ display: "block", fontSize: 11, color: "#64748b", marginTop: 2 }}>
              {approvalSub}
            </span>
          )}
        </span>
      </div>
      {showGeneratedBy && (
        <div style={{ ...row, marginBottom: 0 }}>
          <span style={label}>Generated by</span>
          <span style={value}>
            {formatPersonLine(o.generatedByName, o.generatedByRole) || "—"}
          </span>
        </div>
      )}
    </div>
  );
}
